# Generated by Django 5.1.6 on 2025-03-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='stripe_session_id',
            new_name='payment_session_id',
        ),
    ]
