# Generated by Django 5.1.7 on 2025-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='course_default.png', null=True, upload_to='course-file'),
        ),
    ]
