# Generated by Django 5.1.6 on 2025-03-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_file_alter_variantitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
