# Generated by Django 5.1.6 on 2025-03-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_notification_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_text',
            new_name='text',
        ),
    ]
