# Generated by Django 5.1.6 on 2025-03-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_notification_text_notification_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
    ]
